### ISSUE TITLE
vindum.io link in README is broken

### ISSUE THREAD

**Issue by redbar0n** [funkia/list#107]
The link: http://vindum.io/blog/how-can-list-be-faster-than-native-arrays/

git blame: https://github.com/funkia/list/commit/1a102caef5418089ce92109e4f478bb7b56b62f7

see also: https://github.com/paldepind/vindum.io/issues/1

It would be nice if this blog post were hosted somewhere else, preferably somewhere safe.
I suggest putting it up as a https://dev.to/ blog post.

**Comment by paldepind** [comment]
Thanks. I've fixed the link to point to the new domain.
