### ISSUE TITLE
sort incompatible with Ramda and not curried.

### ISSUE THREAD

**Issue by joelnet** [funkia/list#42]
I saw on the main page list is compatible with ramda's sort function, but have run into problems converting some code to list.

```javascript
const L = require('list/curried')
const R = require('ramda')

const array = [
  { id: 1 },
  { id: 3 },
  { id: 2 },
]

const list = L.fromArray(array)

// ramda sort array
R.sort((a, b) => a.id - b.id, array) //=> [ { id: 1 }, { id: 2 }, { id: 3 } ]

// ramda sort list
R.sort((a, b) => a.id - b.id, list) //=> [ , , ]

// list sort list
L.sort((a, b) => a.id - b.id, list) //=> []
```

I have also noticed `const L = require('list/curried')` does not curry.

```javascript
const sortRamdaId = R.sort((a, b) => a.id - b.id)
const sortListId = L.sort((a, b) => a.id - b.id)

sortRamdaId(array) //=> [ { id: 1 }, { id: 2 }, { id: 3 } ]
sortListId(list) //=> ERROR: sortListId is not a function
```

Am I using this correctly?

**Comment by paldepind** [comment]
Hello @joelnet. This is intentional but it should have been documented.

List's `sort`, `sortBy` and `sortWith` are not equivalent to Ramda's sorting functions. `L.sortWith` is the same as `R.sort`. `L.sort` only takes a single argument and that's why it appears to be non-curried.

The difference is intentional because I think List's approach is better than Ramda's. `L.sort` makes it very easy to sort a list of numbers or strings. And `L.sortWith` gives the same power that `R.sort` does.

I've considered opening an issue on Ramda about having Ramda adopt the same API.

I'd like to hear what you think about it all!

**Comment by joelnet** [comment]
Ahh okay. So my confusion came in from the **Implemented Ramda functions** section, where `sort` is listed under `implemented`. My understanding of this was that it would be equivalent to ramda's sort function.

I went down this path because I am converting some ramda/array code to list. Most other changes went smoothly, but I got stuck on this one.

I wouldn't expect list and ramda to have identical interfaces, but the text sent me down the wrong path.

Changing `sort` to `sortWith` does work great, I did not consider using this because ramda has a different `sortWith` function.

Maybe just an asterisk with a footnote inside the **Implemented Ramda functions** section would be sufficient.

Thanks for your help!

**Comment by paldepind** [comment]
I understand that. Thanks a lot for pointing out the problem. It's clearly not documented properly.

Would you be fine with the current situation as long as the docs are updated to properly explain it? To me the `sort` functions was a trade of between duplicating Ramda and having what I think is a better API. So I choose to diverge slightly from Ramda in that single case.

> I went down this path because I am converting some ramda/array code to list. Most other changes went smoothly, but I got stuck on this one.

If you stumble upon some functions you need that are not implemented please open an issue and I'll do my best to get them implemented swiftly :smile:

**Comment by paldepind** [comment]
Thanks a lot for the feedback :smiley_cat: 

#48 should fix the documentation issue.

> I have some functions that will L.map and then Promise.all. This works great, but of course Promise.all returns an array and not a list. So I have some redundant code that looks like this:

Good point! I definitely think that including something to ease that would be great. `Promise.all` is quite common.

The decorator looks interesting but I think that maybe a `Promise.all` composed with `fromArray` would be simpler? I'd be exactly like `Promise.all` except returning a list. What should such a function be called? `all` is already [taken](https://github.com/funkia/list#every).
