### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by Mottie** [funkia/list#53]
The `dropRepeatsWith` entry in the main readme is incorrect - https://github.com/funkia/list#droprepeats-1

It's listed as `dropRepeats` (missing the `With`), and the code example is shown as `ropRepeatsWith` (missing the `d`).

**Comment by paldepind** [comment]
Thank you for pointing it out :smile:

It should be fixed now. Does it look good to you? https://github.com/funkia/list#droprepeatswith

**Comment by Mottie** [comment]
Awesome!
