### ISSUE TITLE
groupWith seems broken

### ISSUE THREAD

**Issue by grossbart** [funkia/list#60]
I tried to use `groupWith` like so:

```
import * as L from "list/methods";

const xs = L.list({ x: 1 }, { x: 2 }, { x: 3 }, { x: 1 }, { x: 2 }, { x: 3 });
const groupedXs = xs.groupWith((a, b) => {
  console.log(a.x, b.x);
  return a.x === b.x;
});
```

I would have expected this result: `list(list({x: 1}, {x: 1}), list({x: 2}, {x: 2}), list({x: 3}, {x: 3}))`.

But I just got the original list back, nested: `list(list({x: 1}), list({x: 2}), list({x: 3}), list({x: 1}), list({x: 2}), list({x: 3}))`.

What's happening becomes more clear from the `console.log`, which shows what's being compared:

```
1 2
2 3
3 1
1 2
2 3
```

**Comment by paldepind** [comment]
Hello @grossbart. It does indeed look wrong. But, `groupWith` is only supposed to group elements that are next to each other and equal according to the function given. The documentation is not very clear about that :sob: 

For your use case `xs.sortBy(a => a.x).groupBy((a, b) => ...)` should do the trick.

What do you think about that? At the very least the documentation should be improved.

**Comment by grossbart** [comment]
Ah, I see! I read the Ramda docs about the same function and there it is a bit more clear that it is “just“ a pair-wise comparison. Still, it was unexpected to me. Are these “…With“ functions all based on the same idea from other languages, maybe, and I'm just not familiar with them? I checked what `sortWith` does and it seems it does what I expected `groupWith` to do.

Would it maybe make sense to add `groupBy`, which does what I wanted to do and which, through its existence, can more clearly differentiate how `groupWith` differs?

**Comment by paldepind** [comment]
I would like to add `groupBy`. But, I was thinking of making a slight deviation from Ramda by returning a native [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) instead of an object. That would remove the restriction that you can only group by strings and should perform better. What do you think?

Another option would be to also add a `groupSortBy` function that would work like this:

```js
const xs = L.list({ x: 1 }, { x: 2 }, { x: 3 }, { x: 1 }, { x: 2 }, { x: 3 });
xs.groupSortBy(o => o.x);
//=> list(list({x: 1}, {x: 1}), list({x: 2}, {x: 2}), list({x: 3}, {x: 3}))
```

That is, it would be very similar to what you expected `groupWith` to be. However, maybe it is so close to `groupBy` that it is not worth it to have both?

**Comment by grossbart** [comment]
I read up on how Haskell and PureScript do grouping: they, too, rely on data being sorted. It makes sense to me now, as we don't want to sort again if we know that we're dealing with sorted data. So actually, all is good, but a note in the documentation would be nice.

PureScript has sibling functions: `group` needs a sorted list, `group'` sorts internally. Maybe this would be an idea for List as well. https://pursuit.purescript.org/packages/purescript-arrays/5.0.0/docs/Data.Array#v:group'

Regarding your `groupBy` thought: receiving a `Map` would take me by surprise, but not because I'd expect an object but a list of lists … But a map would of course often be what's needed to lookup things and I'd prefer it over an object to be flexible with what values the keys can be. Maybe this is two different functions.

List to me seems inspired by Fantasy Land and the Haskell world, but at the same time from Ramda and some JS patterns. So it's really difficult to find a consistent no-surprises API … I'd appreciate to stick with prior art from Haskell & Co., it's what I look for in libraries like List and `fp-ts`, for instance, because I don't want to subtle differences between libraries (yay, Fantasy Land!). So in this issue I learned that it can make sense to have a requirement to pass a sorted list to `group`, because it gives me the power to do it when I need to; this was unexpected but makes sense.

**Comment by paldepind** [comment]
Thank you for a very thoughtful comment @grossbart :smile:

> PureScript has sibling functions: group needs a sorted list, group' sorts internally. Maybe this would be an idea for List as well.

`group` is already there. `group'` is also nice to have but I don't know what to call it in the absence of `'`.

> Regarding your groupBy thought: receiving a Map would take me by surprise, but not because I'd expect an object but a list of lists … But a map would of course often be what's needed to lookup things and I'd prefer it over an object to be flexible with what values the keys can be. Maybe this is two different functions.

I agree with this. In some sense, a list of lists seems more intuitive but a map can in many cases be more useful.

> List to me seems inspired by Fantasy Land and the Haskell world, but at the same time from Ramda and some JS patterns. So it's really difficult to find a consistent no-surprises API … I'd appreciate to stick with prior art from Haskell & Co., it's what I look for in libraries like List and fp-ts, for instance, because I don't want to subtle differences between libraries (yay, Fantasy Land!). So in this issue I learned that it can make sense to have a requirement to pass a sorted list to group, because it gives me the power to do it when I need to; this was unexpected but makes sense.

Yes, there is a lot of prior art with many inconsistencies. Among other things, the names `bind`, `flatMap`, and `chain` all denote the same function. I've tried to make the API as familiar as possible to as many people as possible. If you feel that List can do a better job at this, please let me know. Ramda has had the biggest influence which itself is hugely influenced by Haskell. In a few cases, I've added aliases. For instance, List has both `reduceRight` and `foldr` which is the same function.

**Comment by grossbart** [comment]
Thanks for elaborating on your thinking, @paldepind, and for clarifying the documentation – it's clear now 👍And sorry for only getting back to you so late, as is sometimes the case, deadlines and vacation got in the way 😅
