### ISSUE TITLE
Stop mutating

### ISSUE THREAD

**Issue by Levino** [funkia/list#77]
You mutate arguments. That is "unfunctional and bad style".

Examples:

https://github.com/funkia/list/blob/b626bb5139e10e4bdfe7dfc778509d177d4e5df0/src/index.ts#L982-L991

This should be fixed and never be done again. Actually **nothing** should ever be mutated in the whole codebase of this library.

**Comment by paldepind** [comment]
The code in your example doesn't mutate the values it receives as argument. It merely reassigns to the argument.

Also, internal mutations are fine. The API of List is 100% pure and functional. There is zero reason to implement all the internals in a purely functional style. That would slow down the library with no benefits.

**Comment by Levino** [comment]
Thank you for the explanation. You are right, no mutation, sorry. I still do not like the current style but I guess the performance argument holds. Closing as 'wontfix'.
