### ISSUE TITLE
Can't find fromArray

### ISSUE THREAD

**Issue by Freak613** [funkia/list#79]
Library seems to not export nor having `fromArray` function.
Specifically, I'm trying to import it as ES-module and bundled dist from npm doesn't have this function in exports.

**Comment by paldepind** [comment]
Hi @Freak613. The function has been renamed to just `from`. I've forgot to update the documentation :sweat:

**Comment by paldepind** [comment]
I've no updated the documentation to reflect the fact that `fromArray` and `fromIterable` was merged into a single function called `from.`
