### ISSUE TITLE
head() is missing?

### ISSUE THREAD

**Issue by shomodj** [funkia/list#82]
Is it just me or head is missing in all type definitions? and code?

documentation mentions it as an alias for first?

list version 2.0.18

thanks

**Comment by paldepind** [comment]
Hi @shomodj. Thank you for pointing this out. It is definitely completely missing.

**Comment by paldepind** [comment]
This should now be fixed in the [latest release 2.0.19](https://github.com/funkia/list/releases/tag/v2.0.19). Please confirm that it works then we can close the issue :smile:

**Comment by shomodj** [comment]
typescript confirms its there ;)
